# Default values for momo-product-lnd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replica: 2
service: momo-product-lnd
namespace: momovn
image: docker.mservice.io/momovn-dev/eks/momo-product-lnd
host: momovn-dev.mservice.io
autoscaling: false
minReplicas: 2
maxReplicas: 5
servicePort: 8000
basePath: /lnd
startCommand: yarn start-and-revalidate-uat
envType: uat
